import cv2, threading, sys
# import camera_opencv

from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5 import QtGui

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtMultimedia import *

class MyWindow(QMainWindow):
    def setupUi(self, MainWindow) :
        super().__init__()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cctv_box = QtWidgets.QGroupBox(self.centralwidget)
        self.cctv_box.setGeometry(QtCore.QRect(30, 50, 271, 171))
        self.cctv_box.setObjectName("cctv_box")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.cctv_box)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(self.live_webcam_click_on)

        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.live_webcam_click_off)


        self.verticalLayoutWidget = QtWidgets.QWidget(self.cctv_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 121, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.cctv_box)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 80, 121, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.webcam_box = QtWidgets.QGroupBox(self.centralwidget)
        self.webcam_box.setGeometry(QtCore.QRect(320, 50, 851, 491))
        self.webcam_box.setObjectName("webcam_box")
        self.webcam_frame = QtWidgets.QFrame(self.webcam_box)
        self.webcam_frame.setGeometry(QtCore.QRect(20, 30, 811, 441))
        self.webcam_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.webcam_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.webcam_frame.setLineWidth(2)
        self.webcam_frame.setObjectName("webcam_frame")
        self.email_box = QtWidgets.QGroupBox(self.centralwidget)
        self.email_box.setGeometry(QtCore.QRect(30, 240, 271, 80))
        self.email_box.setObjectName("email_box")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.email_box)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.database_box = QtWidgets.QGroupBox(self.centralwidget)
        self.database_box.setGeometry(QtCore.QRect(30, 350, 271, 80))
        self.database_box.setObjectName("database_box")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.database_box)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.data_box = QtWidgets.QGroupBox(self.centralwidget)
        self.data_box.setGeometry(QtCore.QRect(30, 460, 271, 80))
        self.data_box.setObjectName("data_box")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.data_box)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def live_webcam_click_off(self) :
        QMessageBox.about(self, 'message', '카메라 끄기')

    def live_webcam_click_on(self) :
        QMessageBox.about(self, 'message', '카메라 켜기')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cctv_box.setTitle(_translate("MainWindow", "01. CCTV Mode"))
        self.pushButton_2.setText(_translate("MainWindow", "on"))
        self.pushButton.setText(_translate("MainWindow", "off"))
        self.checkBox.setText(_translate("MainWindow", "Drone"))
        self.checkBox_2.setText(_translate("MainWindow", "Airplane"))
        self.checkBox_3.setText(_translate("MainWindow", "Helicopter"))
        self.checkBox_4.setText(_translate("MainWindow", "Military Drone"))
        self.checkBox_5.setText(_translate("MainWindow", "Bird"))
        self.checkBox_6.setText(_translate("MainWindow", "Balloon"))
        self.webcam_box.setTitle(_translate("MainWindow", "Live Webcam"))
        self.email_box.setTitle(_translate("MainWindow", "02. Email System"))
        self.pushButton_5.setText(_translate("MainWindow", "Start"))
        self.database_box.setTitle(_translate("MainWindow", "03. Database"))
        self.pushButton_6.setText(_translate("MainWindow", "Start"))
        self.data_box.setTitle(_translate("MainWindow", "04. Data Analysis"))
        self.pushButton_7.setText(_translate("MainWindow", "Start"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MyWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())